security:
    encoders:
        App\Entity\Personne: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Personne
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                #obliger la connection     
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
